### ISSUE TITLE
可否增加使用系统代理连接的选项

### ISSUE THREAD

**Issue by KagamiChan** [poooi/plugin-k2badge#2]
应该是自己的网络问题，最近直接连接的速度很慢，慢到无法完成加载
所以问一下是否方便加入使用系统代理连接的选项
不好实现的话，我就自己架设一个反代好了

**Comment by KochiyaOcean** [comment]
默认应该是通过的啊……

**Comment by KagamiChan** [comment]
嗯……难道是因为通过代理才这么慢……我再查查看

**Comment by KagamiChan** [comment]
试了一下的确是经过了代理的……看来只能用反代了
多谢

**Comment by KagamiChan** [comment]
看了一下开发者工具，感觉应该是我的 electron 1.3.2 没升级的原因，在原来的情况下会莫名其妙出现 content length mismatch 之类的问题，换到 1.3.5 就好了……
再次感谢
